### PR TITLE
clams.source module for MMIF pipeline sources

### PR DESCRIPTION
**Pull request by keighrim**
This PR to add a generator for an "empty" MMIF string that has *no* views but any number of `Document`s to start with.

### CODE REVIEW

**Comment by angus-lherrou** [comment]
@keighrim, if you're not already working on updating this branch to use the MMIF Python 0.2.0 API, I can do that tomorrow

**Comment by keighrim** [comment]
I haven't worked on this. Please feel free to update to 0.2.0. Thanks!

**Comment by angus-lherrou** [comment]
Added the ability to create a pipeline that generates MMIF objects with common documents and metadata between them

**Comment by angus-lherrou** [comment]
@marcverhagen, @keighrim, could you take a look at the additions I've made and suggest any changes?

**Review by marcverhagen — APPROVED** [review]
Nothing funky jumps out at me, but I am hardly proficient in this part of the code.

**Comment by keighrim** [comment]
All looked good. I added very minor refactoring. I think this is ready for merge.

**Pull request merged**
