### PR TITLE
initial implementation of parameterized `annotate`

### PR DESCRIPTION
**Pull request by keighrim**
This PR contains some breaking changes. See #29 for discussions.

### CODE REVIEW

**Comment by keighrim** [comment]
Changes here will break existing CLASM apps, so I want everyone to review them.

**Review by marcverhagen — APPROVED** [review]
Looks good to me, the only question I have is why the sniff method is still in there.

**Comment by keighrim** [comment]
Good pint. I unbound `sniff` to a HTTP verb. but I didn't actually remove `sniff` as we didn't exactly decide what to do with it (#21). However, it would be much clear to take it out once and for all. We can always re-introduce it if we need.

**Comment by keighrim** [comment]
How about method names? In short, we have 
* "public" `appmetadata` method wraps `setupmetadata` and 
* "public" `annotate` method wraps `_annotate`. 

and HTTP verbs are bound to those "public" methods. For visual parity between them, I'd like to suggest we use `_appmetadata` (instead of `setupmetadata`) as "private" counterpart for `appmetadata`

**Comment by marcverhagen** [comment]
Ah, the names. They seem fine, but I have some unease. With `appmetadata` I feel that the `app` prefix doesn't do us any good, we could use `metadata` or `get_metadata`.

Also, I don't see `appmetadata` wrapping `setupmetadata`.

If `appmetdata` or `metadata` was wrapping something then maybe it should wrap `_metadata` so we make it similar to `annotate` and `_annotate`.

So we have:
- public `annotate` method wraps `_annotate`
- public `metadata` method wraps `_metadata`

**Pull request merged**
