### PR TITLE
Adding appmetadata schema

### PR DESCRIPTION
**Pull request by keighrim**
This PR addresses #49, #52, and clamsproject/clams-apps#18 . Concretely, app metadata is defined as python objects (in `clams/appmetadata/__init__.py`) and *exported* as a JSON file while building documentation ([here](https://github.com/clamsproject/clams-python/compare/develop...49-metadata-schema?expand=1#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R46)). Generated JSON schema file has `$comment` field where developers can store the version of SDK used. At the moment, I don't see a point to keep a separate versioning for the schema, but if you use the same version string between the python SDK and app metadata schema, we need to carefully think through the compatibility issues when app metadata scheme is updated in the public branch. For now, input and output specifications are not handled. 

Here's the schema as defined now. 

``` json
{
  "title": "CLAMS AppMetadata",
  "description": "CLAMS AppMetadata defines metadata model that describes a CLAMS app",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "app_version": {
      "type": "string"
    },
    "mmif_version": {
      "default": "0.3.1",
      "type": "string"
    },
    "wrapper_version": {
      "type": "string"
    },
    "license": {
      "type": "string"
    },
    "wrapper_license": {
      "type": "string"
    },
    "url": {
      "minLength": 1,
      "maxLength": 65536,
      "format": "uri",
      "type": "string"
    },
    "input": {
      "type": "array",
      "items": {}
    },
    "output": {
      "type": "array",
      "items": {}
    }
  },
  "required": [
    "name",
    "description",
    "app_version",
    "license",
    "url",
    "input",
    "output"
  ],
  "additionalProperties": false,
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$comment": "clams-python SDK 0.2.3.dev1 was used to generate this schema"
}
```

And here's the metadata for [the example app used in the test suite](https://github.com/clamsproject/clams-python/compare/develop...49-metadata-schema?expand=1#diff-013ad51826f008ee90054b1c5c5f6e307f980374fb694814e8732e7ce5274fa5R77-R87). 

``` json
{
    "name": "Example CLAMS App for testing",
    "description": "This app doesn't do anything",
    "app_version": "0.0.1",
    "license": "MIT",
    "url": "https://apps.clams.ai/example/0.0.1",
    "input": [],
    "output": []
}
```

### CODE REVIEW

**Comment by keighrim** [comment]
added a new commit that implements I/O specification. This change is a breaking one, so I had to abandon a few lines of backward compatibility (e.g. [this](https://github.com/clamsproject/clams-python/pull/53/commits/0e6a6b5fa660d92ca29c1f140f296060e7af3a2d#diff-506e5477ce240ed2c17b62a5ab6cd1cdc4de7148b1cfdac6eec35d5b7c9ab855L23-R23) ) to make the code simple and more readable. With addition of I/O specs, the schema now looks like 
``` json 
{
  "title": "CLAMS AppMetadata",
  "description": "Defines a data model that describes a CLAMS app",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "app_version": {
      "type": "string"
    },
    "mmif_version": {
      "default": "0.3.1",
      "type": "string"
    },
    "wrapper_version": {
      "type": "string"
    },
    "license": {
      "type": "string"
    },
    "wrapper_license": {
      "type": "string"
    },
    "url": {
      "minLength": 1,
      "maxLength": 65536,
      "format": "uri",
      "type": "string"
    },
    "input": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Input"
      }
    },
    "output": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Output"
      }
    }
  },
  "required": [
    "name",
    "description",
    "app_version",
    "license",
    "url",
    "input",
    "output"
  ],
  "additionalProperties": false,
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$comment": "clams-python SDK 0.2.3.dev1 was used to generate this schema",
  "definitions": {
    "Input": {
      "title": "CLAMS Input Specification",
      "description": "Defines a data model that describes input specification of a CLAMS app",
      "type": "object",
      "properties": {
        "@type": {
          "minLength": 1,
          "maxLength": 65536,
          "format": "uri",
          "type": "string"
        },
        "properties": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "required": {
          "default": true,
          "type": "boolean"
        }
      },
      "additionalProperties": false
    },
    "Output": {
      "title": "CLAMS Output Specification",
      "description": "Defines a data model that describes output specification of a CLAMS app",
      "type": "object",
      "properties": {
        "@type": {
          "minLength": 1,
          "maxLength": 65536,
          "format": "uri",
          "type": "string"
        },
        "properties": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        }
      },
      "additionalProperties": false
    }
  }
}
```

And the new example app metadata. 
``` json
{
  "name": "Example CLAMS App for testing",
  "description": "This app doesn't do anything",
  "app_version": "0.0.1",
  "license": "MIT",
  "url": "https://apps.clams.ai/example/0.0.1",
  "input": [],
  "output": [
    {
      "@type": "http://mmif.clams.ai/0.3.0/vocabulary/TimeFrame"
    }
  ]
}
```

**Comment by keighrim** [comment]
Please take a look and let me know if anything is missing or needs fixes.

**Comment by keighrim** [comment]
#29 suggests including `parameters` in the app metadata. With this implementation of `_input_spec()`, automatically adding parameter information for *optional* input types are very doable. Other parameters (runtime configurations such as [these](https://github.com/clamsproject/app-slatedetection/blob/de7c60b101815ed6532ddcf77e0237ee7b75b619/app.py#L52-L55)), however, have to be added in another way. For example, https://github.com/clamsproject/clams-python/issues/29#issue-742921287 suggests using docstring for automatic population of `parameters` in the app metadata.

**Comment by keighrim** [comment]
We might also want to consider using term `iri` instead of `url` for the app identifier, although according to our plan, apps will have valid html pages (under the app directory) linked to the identifier. Any thoughts?

**Comment by keighrim** [comment]
A couple things we talked in today's meeting: 
- Remove `_input_spec()` and `_output_spec()` methods - every metadata population operations should happens just in a single `_appmetadata()` method.
- AppMetadata object should be able to initiated from a plain python dict, or a pre-built json string

**Comment by keighrim** [comment]
Commits are added to address out recent discussion. [Here's](https://github.com/clamsproject/clams-python/pull/53/files#diff-013ad51826f008ee90054b1c5c5f6e307f980374fb694814e8732e7ce5274fa5R62-R80) an example code to set metadata for an app. @kelleyl @marcverhagen please take a look at the example code and let me how you think. 
This is output of `appmetadata(pretty=True)`
``` json 
{
  "name": "Example CLAMS App for testing",
  "description": "This app doesn't do anything",
  "app_version": "0.0.1",
  "mmif_version": "0.3.3",
  "license": "MIT",
  "identifier": "https://apps.clams.ai/example/0.0.1",
  "input": [
    {
      "@type": "http://mmif.clams.ai/0.3.1/vocabulary/AudioDocument",
      "required": true
    }
  ],
  "output": [
    {
      "@type": "http://mmif.clams.ai/0.3.1/vocabulary/TimeFrame"
    },
    {
      "@type": "http://mmif.clams.ai/0.3.1/vocabulary/BoundingBox",
      "properties": {}
    }
  ],
  "parameters": [
    {
      "name": "raise_error",
      "value": {
        "datatype": "boolean",
        "default": "false"
      },
      "description": "force raise a ValueError"
    },
    {
      "name": "multiple_choice",
      "value": {
        "datatype": "integer",
        "choices": [
          1,
          2,
          3,
          4,
          5
        ],
        "default": 3
      },
      "description": "force raise a ValueError"
    }
  ]
}
```

**Comment by keighrim** [comment]
I actually believe that `add_input`, `add_output`, and `add_parameter` methods add some value in that; 

1. When adding a simple I/O spec that has only a `@type`, code can be much simpler 
``` python
m = AppMetadata( 
  ...
  input = [ {'at_type': Types.TimeFrame}]
  ...
)

# vs. 
m = AppMetadata( 
  ...
  # omitting `input=` will initialize input as an empty list 
)
m.add_input(Types.TimeFrames)

# note that the first method still works and that will best serve for reading in pre-written metadata (e.g. from a JSON file)
```
2. `input`, `output`, and `parameters` are all implemented as lists so having safeguards (`add_xxx` methods) that check for duplicate is not a bad idea. 
2. When adding an *optional* input type, `add_input` implementation can automatically register the type as a runtime parameter. This feature is not implemented at the moment (https://github.com/clamsproject/clams-python/blob/5d9b87626f91d9942af190a09e99938a7c34988f/clams/appmetadata/__init__.py#L122-L125).

**Comment by marcverhagen** [comment]
Okay, there is some advantage to that. Let's roll with it. 

Quick clarification, you wrote

```python
input = [ {'at_type': Types.TimeFrame}]
```

Should that be

```python
input = [ {'@type': Types.TimeFrame}]
```

**Review by marcverhagen — COMMENTED** [review]
I couldn't really see where the changes for the new parameter lists are. Input and output looks good when I look at the test example but AppMetadata still has it as a list of Input/Output instances, I think I am missing something there.

**Comment by keighrim** [comment]
You're not missing anything, I guess. The `Input` and `Output` (and `RuntimeParameter`) classes are still there and `AppMetadata` is relying on those classes for internal operations. The example shows that users (developers) do not have to anything about the existence (or usage) of those classes to use `AppMetadata`. I wish I could make `Input` / `Output` classes private, but I can't. I'm justing adding a underscore to mark them as private.

**Comment by keighrim** [comment]
Having `_Input`, `_Output`, and `_RuntimeParameter` (marked with underscores) resulted in those underscores appearing in the exported jsonschema file (using `pydantic`, see a code block below), and I don't like them. 
I wonder whether marking them *private* is really necessary, even I have hidden those classes behind 
python methods. 

``` json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$comment": "clams-python SDK 0.2.2 was used to generate this schema",
  "title": "CLAMS AppMetadata",
  "description": "Defines a data model that describes a CLAMS app",
  "type": "object",
  "properties": {
    "name": {
      "description": "A short name of the app",
      "type": "string"
      ...
  },
  "required": [
    "name",
    "description",
    "app_version",
    "license",
    "identifier"
  ],
  "additionalProperties": false,
  "definitions": {
    "_Input": { # oops
      "title": "CLAMS Input Specification",
      "description": "Defines a data model that describes input specification of a CLAMS app",
      "type": "object",
      "properties": {
          ...
      },
      "required": [
        "@type"
      ],
      "additionalProperties": false
    },
    "_Output": { # oops
        ...
    },
    "_RuntimeParameter": { # oops
        ...
    }
  }
}
```

**Comment by marcverhagen** [comment]
I think that using `Input`, `Output` and `RuntimeParameter` as class names is totally fine. Especially since the notion of *private* is somewhat weird in Python anyway.

**Comment by keighrim** [comment]
Renamed back, added documentation. I think this one is ready to merge.

**Pull request merged**
